# Generated by Django 4.0.5 on 2022-06-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(max_length=350, verbose_name='Контент')),
                ('author', models.CharField(default='Unknown', max_length=20, verbose_name='Автор')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='Создание времени')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
            ],
        ),
    ]
